n=int(input('diga um numero'))
a=n*int(1)
b=n*int(2)
c=n*int(3)
d=n*int(4)
e=n*int(5)
f=n*int(6)
g=n*int(7)
h=n*int(8)
i=n*int(9)
j=n*int(10)

print('a tabuado do numero é {}x1 é {},{}x2 é {},{}x3 é {}, {}x4 é {}, {}x5 é{}, {}x6 é {}, {}x7 é{}, {}x8 é {},{}x9 é{}, {}x10 é {}'.format(n,a,n,b,n,c,n,d,n,e,n,f,n,g,n,h,n,i,n,j))
